FROM golang:alpine AS builder

WORKDIR /src
COPY . .

RUN apk add --no-cache curl git make
RUN make V=1 bin/step-sds

FROM smallstep/step-cli:latest

COPY --from=builder /src/bin/step-sds "/usr/local/bin/step-sds"

STOPSIGNAL SIGTERM

CMD /bin/bash
