FROM smallstep/step-cli:0.22.0

RUN mkdir /src
ADD . /src

RUN apk add --no-cache make git curl && \
	cd /src && \
	mkdir -p output/bin && \
	make V=1 bin/step-sds

COPY --from=builder /src/bin/step-sds "/usr/local/bin/step-sds"

STOPSIGNAL SIGTERM

CMD /bin/bash
